// <auto-generated />
using System;
using FIS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FIS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FisDbContext))]
    [Migration("20260429124725_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FIS.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("CodigoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codigo_cliente");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NitCi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nit_ci");

                    b.Property<string>("NombreRazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre_razon_social");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("tipo_cliente");

                    b.HasKey("IdCliente");

                    b.HasIndex("CodigoCliente")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_CLIENTE_email");

                    b.HasIndex("NitCi")
                        .IsUnique()
                        .HasDatabaseName("IX_CLIENTE_nit");

                    b.HasIndex("NombreRazonSocial")
                        .HasDatabaseName("IX_CLIENTE_nombre");

                    b.HasIndex("Telefono")
                        .HasDatabaseName("IX_CLIENTE_telefono");

                    b.ToTable("CLIENTE", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_CLIENTE_tipo", "tipo_cliente IN ('N','J')");
                        });
                });

            modelBuilder.Entity("FIS.Domain.Entities.Contrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_contrato");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContrato"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("activo")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdPlan")
                        .HasColumnType("int")
                        .HasColumnName("id_plan");

                    b.Property<int>("IdUsuarioRegistro")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_registro");

                    b.Property<string>("NumeroContrato")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("numero_contrato");

                    b.HasKey("IdContrato");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("IX_CONTRATO_cliente");

                    b.HasIndex("IdPlan");

                    b.HasIndex("IdUsuarioRegistro");

                    b.HasIndex("NumeroContrato")
                        .IsUnique();

                    b.ToTable("CONTRATO", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_CONTRATO_estado", "estado IN ('activo','suspendido','finalizado','cancelado')");

                            t.HasCheckConstraint("CK_CONTRATO_fechas", "fecha_fin > fecha_inicio");
                        });
                });

            modelBuilder.Entity("FIS.Domain.Entities.Mora", b =>
                {
                    b.Property<int>("IdMora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_mora");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMora"));

                    b.Property<bool>("EnMora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("en_mora");

                    b.Property<DateTime?>("FechaInicioMora")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio_mora");

                    b.Property<DateTime?>("FechaRegularizacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_regularizacion");

                    b.Property<int>("IdContrato")
                        .HasColumnType("int")
                        .HasColumnName("id_contrato");

                    b.Property<decimal>("MontoAdeudado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("monto_adeudado");

                    b.Property<bool>("ServicioCortado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("servicio_cortado");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("IdMora");

                    b.HasIndex("IdContrato")
                        .IsUnique();

                    b.ToTable("MORA", "dbo");
                });

            modelBuilder.Entity("FIS.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<bool>("Anulado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("anulado");

                    b.Property<string>("Conceptos")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("conceptos");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_anulacion");

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_pago")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdCajero")
                        .HasColumnType("int")
                        .HasColumnName("id_cajero");

                    b.Property<int>("IdContrato")
                        .HasColumnType("int")
                        .HasColumnName("id_contrato");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("MontoMora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("monto_mora");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_total");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("motivo_anulacion");

                    b.Property<string>("NumeroRecibo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("numero_recibo");

                    b.Property<short>("PeriodoAnio")
                        .HasColumnType("smallint")
                        .HasColumnName("periodo_anio");

                    b.Property<byte>("PeriodoMes")
                        .HasColumnType("tinyint")
                        .HasColumnName("periodo_mes");

                    b.HasKey("IdPago");

                    b.HasIndex("IdCajero");

                    b.HasIndex("IdContrato");

                    b.HasIndex("NumeroRecibo")
                        .IsUnique();

                    b.ToTable("PAGO", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_PAGO_metodo", "metodo_pago IN ('Efectivo','QR','Transferencia','Tarjeta Débito','Tarjeta Crédito')");

                            t.HasCheckConstraint("CK_PAGO_periodo_mes", "periodo_mes BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("FIS.Domain.Entities.PlanServicio", b =>
                {
                    b.Property<int>("IdPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_plan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlan"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("NombrePlan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_plan");

                    b.Property<decimal>("PrecioMensual")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_mensual");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tipo_servicio");

                    b.Property<decimal?>("VelocidadBajadaMbps")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("velocidad_bajada_mbps");

                    b.Property<decimal?>("VelocidadSubidaMbps")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("velocidad_subida_mbps");

                    b.HasKey("IdPlan");

                    b.ToTable("PLAN_SERVICIO", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_PLAN_tipo_servicio", "tipo_servicio IN ('Internet Residencial','Internet Empresarial','Hosting Web','Dominio .bo','Correo Corporativo')");
                        });
                });

            modelBuilder.Entity("FIS.Domain.Entities.Reclamo", b =>
                {
                    b.Property<int>("IdReclamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reclamo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReclamo"));

                    b.Property<byte?>("Calificacion")
                        .HasColumnType("tinyint")
                        .HasColumnName("calificacion");

                    b.Property<string>("CanalEntrada")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("telefono")
                        .HasColumnName("canal_entrada");

                    b.Property<string>("DescripcionProblema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion_problema");

                    b.Property<int?>("DuracionAudioSeg")
                        .HasColumnType("int")
                        .HasColumnName("duracion_audio_seg");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("Recepcionado")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaApertura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_apertura")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_cierre");

                    b.Property<string>("HashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("hash_sha256");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdContrato")
                        .HasColumnType("int")
                        .HasColumnName("id_contrato");

                    b.Property<int?>("IdTecnico")
                        .HasColumnType("int")
                        .HasColumnName("id_tecnico");

                    b.Property<int>("IdUsuarioRegistro")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_registro");

                    b.Property<string>("NumeroReclamo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("numero_reclamo");

                    b.Property<byte>("Prioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)3)
                        .HasColumnName("prioridad");

                    b.Property<string>("RutaAudio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ruta_audio");

                    b.Property<string>("SolucionAplicada")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("solucion_aplicada");

                    b.Property<int?>("TiempoRespuestaMin")
                        .HasColumnType("int")
                        .HasColumnName("tiempo_respuesta_min");

                    b.Property<string>("TipoReclamo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo_reclamo");

                    b.HasKey("IdReclamo");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdContrato");

                    b.HasIndex("IdTecnico");

                    b.HasIndex("IdUsuarioRegistro");

                    b.HasIndex("NumeroReclamo")
                        .IsUnique();

                    b.ToTable("RECLAMO", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_RECLAMO_calificacion", "calificacion IS NULL OR (calificacion BETWEEN 1 AND 5)");

                            t.HasCheckConstraint("CK_RECLAMO_canal", "canal_entrada IN ('telefono','web','presencial','app')");

                            t.HasCheckConstraint("CK_RECLAMO_estado", "estado IN ('Recepcionado','En Proceso','Observado','Cerrado')");

                            t.HasCheckConstraint("CK_RECLAMO_prioridad", "prioridad BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_RECLAMO_tipo", "tipo_reclamo IN ('Leve','Medio','Complejo')");
                        });
                });

            modelBuilder.Entity("FIS.Domain.Entities.Rol", b =>
                {
                    b.Property<byte>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("IdRol"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("ROL", "dbo");
                });

            modelBuilder.Entity("FIS.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("datetime2")
                        .HasColumnName("bloqueado_hasta");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("especialidad");

                    b.Property<byte>("IdRol")
                        .HasColumnType("tinyint")
                        .HasColumnName("id_rol");

                    b.Property<byte>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_USUARIO_email");

                    b.HasIndex("IdRol");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USUARIO", "dbo");
                });

            modelBuilder.Entity("FIS.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("FIS.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Contratos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FIS.Domain.Entities.PlanServicio", "Plan")
                        .WithMany("Contratos")
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FIS.Domain.Entities.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioRegistro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Plan");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("FIS.Domain.Entities.Mora", b =>
                {
                    b.HasOne("FIS.Domain.Entities.Contrato", "Contrato")
                        .WithOne("Mora")
                        .HasForeignKey("FIS.Domain.Entities.Mora", "IdContrato")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("FIS.Domain.Entities.Pago", b =>
                {
                    b.HasOne("FIS.Domain.Entities.Usuario", "Cajero")
                        .WithMany()
                        .HasForeignKey("IdCajero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FIS.Domain.Entities.Contrato", "Contrato")
                        .WithMany("Pagos")
                        .HasForeignKey("IdContrato")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cajero");

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("FIS.Domain.Entities.Reclamo", b =>
                {
                    b.HasOne("FIS.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Reclamos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FIS.Domain.Entities.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("IdContrato")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FIS.Domain.Entities.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("IdTecnico")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FIS.Domain.Entities.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioRegistro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Contrato");

                    b.Navigation("Tecnico");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("FIS.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("FIS.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("FIS.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Reclamos");
                });

            modelBuilder.Entity("FIS.Domain.Entities.Contrato", b =>
                {
                    b.Navigation("Mora");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("FIS.Domain.Entities.PlanServicio", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("FIS.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
