mindmap
  root((FIS))
    Funcional 18
      Autenticación HU01
      Clientes HU03
      Servicios HU04
      Contratos HU05
      Pagos HU07-HU09
      Mora HU10
      Reclamos HU14-HU17
      Reportes HU20-HU22
    No Funcional 14
      Seguridad
        RBAC
        Cifrado
        BCrypt
      Rendimiento
        3s respuesta
        99% uptime
      Datos
        3FN
        Backups
      Escalabilidad
        Multi-instance
        Cache
